export const pageTitles = {
   '/menu': 'Viandas Cook',
   '/descuentos': 'Descuentos',
   '/cart': 'Carrito',
   '/cart/empty': 'Carrito',
   '/checkout#': '¡Último Paso!',
   '/checkout': '¡Último Paso!',
   '/checkout/address': 'Dirección de envío',
   '/checkout/promociones': 'Promos Vigentes',
   '/checkout/canjear-puntos': 'Canjear Puntos',
   '/checkout/delivery': 'Fecha de Entrega',
   '/mi-cuenta': 'Mi Cuenta',
   '/mi-cuenta/perfil': 'Perfil',
   '/mi-cuenta/invitar-amigos': 'Invitar Amigos',
};
