export const pageTitles = {
   '/menu': 'Viandas Cook',
   '/descuentos': 'Descuentos',
   '/cart': 'Carrito',
   '/cart/empty': 'Carrito',
   '/checkout#': '¡Último Paso!',
   '/checkout': '¡Último Paso!',
   '/checkout/address': 'Dirección de envío',
   '/checkout/promociones': 'Promos Vigentes',
   '/checkout/referido': 'Referido',
   '/checkout/canjear-puntos': 'Canjear Puntos',
   '/checkout/delivery': 'Fecha de Entrega',
   '/mi-cuenta': 'Mi Cuenta',
   '/mi-cuenta/perfil': 'Perfil',
   '/mi-cuenta/puntos': 'Puntos Acumulados',
   '/mi-cuenta/invitar-amigos': 'Invitar Amigos',
   '/mi-cuenta/password': 'Cambiar Clave',
   '/como-funciona': '¿Cómo Funciona?',
   '/nosotros': 'Nosotros',
   '/preguntas': '¿Preguntas?',
   '/loyalty': '¡Sumá puntos!',
};
